#
# YAML config file for AnalysisPlotter
# have a look e.g. to https://camel.readthedocs.io/en/latest/yamlref.html for a general reference to YAML
#
settings:
  input_path: /nfs/dust/cms/user/froehlia/BstarToTW/Run2_102X_v1/Analysis/Muon/all/NOMINAL/
  file_prefix: uhh2.AnalysisModuleRunner.
  output_path: ./plots/
  b_CMS: True                    # draw "CMS" on plot
  cms_position: center         # predefined position where to draw "CMS" on the plot 
  cms_extratext: Preliminary   # only works when b_CMS is True, extra text is drawn below CMS
  infotext: 137.2/fb (13 TeV) # info text to be drawn on top of the plot

processes:
  - process: data
    file_name: DATA.DATA.root
    style: data
    color: 1
  - process: tbar
    hist_name: t#bar{t}
    file_name: MC.TT.root
    style: fill
    color: 400
  - process: singletop
    hist_name: Single top
    file_name: MC.ST.root
    style: fill
    color: 768
  - process: nontop
    hist_name: Other
    file_name: MC.NonTop.root
    style: fill
    color: 632

stack:
  stack_list: [ttbar, singletop, nontop]
